### ISSUE TITLE
error using MEX issue

### ISSUE THREAD

**Issue by ragyei** [FranckLab/FIDVC#23]
Hi, please find attached the following error message during my use of the FIDVC code. 
Any reason for this?
Thank you.
Ron.

**************************************************************************************************************

Building with 'g++'.
Error using mex
/scratch/brown/ragyei/DVC_CODE/FIDVC-master_2/FIDVC-master/mirt3D_mexinterp.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
/scratch/brown/ragyei/DVC_CODE/FIDVC-master_2/FIDVC-master/mirt3D_mexinterp.cpp:173:11: error: cannot convert ‘const size_t* {aka const long unsigned int*}’ to ‘const int*’ in assignment
     Xdims = mxGetDimensions(IN_S);
           ^
/scratch/brown/ragyei/DVC_CODE/FIDVC-master_2/FIDVC-master/mirt3D_mexinterp.cpp:177:10: error: cannot convert ‘const size_t* {aka const long unsigned int*}’ to ‘const int*’ in assignment
     dims = mxGetDimensions(IN_Z);
          ^
/scratch/brown/ragyei/DVC_CODE/FIDVC-master_2/FIDVC-master/mirt3D_mexinterp.cpp:203:75: error: cannot convert ‘int*’ to ‘const size_t* {aka const long unsigned int*}’ for argument ‘2’ to ‘mxArray*
mxCreateNumericArray(size_t, const size_t*, mxClassID, mxComplexity)’
     OUT_F = mxCreateNumericArray(newXndim, newdims, mxDOUBLE_CLASS, mxREAL);
                                                                           ^

Error in mirt3D_mexinterp (line 37)
mex(pathtofile,'-outdir',pathstr);

Error in volumeMapping (line 52)
for i = 1:3, u{i} = mirt3D_mexinterp(u0{i}, m_u0{1}, m_u0{2}, m_u0{3}); end

Error in IDVC_3 (line 89)
        I = volumeMapping(I,m,u);

Error in funIDVC_3 (line 67)
    [u_, cc{i-1}, dm, m] = IDVC_3(I,sSize0,u_);

Error in exampleRunFile_3 (line 80)
    [u, cc, dm, m] = funIDVC_3(filename, sSize_rows(ii,:), incORcum);

**Comment by ALandauer** [comment]
Hi Ron,
We use a precompliled mex function to speed up 3D interpolation. In recent desktop versions of Matlab (for Windows version especially) this usually works fairly seamlessly, but other environments will often need to recompile the mex function using appropriate local settings. It looks like you are trying to run this in an environment were Matlab is configured to use the 'g++' compiler, which seems to have a slightly different feature set and is not typically compatible. See the "Running FIDVC" section in the readme.  In generally getting a mex to run properly is outside our expertise. 

If, for some reason, you cannot get mex files to work properly, it is possible that you could rewrite the interpolation step such that the mex is not needed. In that case, you would need to make sure to validate your results, because interpolation settings may influence final accuracy, and the code may be noticeably slower.

Did you get this running on our example dataset, or only with our own? Occasionally, datasets will cause errors in the interpolation and Matlab will still throw a relatively generic mex error. In this case, we can discuss with you what your images look like and try to diagnose what the issue is.

Regards,
Alex
