### ISSUE TITLE
Computing DVC displacements

### ISSUE THREAD

**Issue by ObonuAdaklu** [FranckLab/FIDVC#25]
Hi, 

Thank you for the FIDVC code!
I will be happy for this clarification.
(A) The FIDVC compares corresponding interrogation windows (between undeformed and deformed image volumes) and measures the displacement components du1,du2,and du3 that best matches each respective corresponding interrogation window.  I believe these values are then spatially linked to the  center of the each corresponding window. 

(B) Then to obtain displacements at every specified "dm", the code then performs a linear interpolation between the co-ordinates of the interrogation window centers which have computed values of du1,du2 and du3. 

(C) If point (B) is true is it fine to say that in order to get that actual displacement at each point one needs to further decrease the sub-set spacing so that the interpolation does not affect the true interpolation ?

(D) Finally will be advisable to change the minimum subset spacing to a fixed value say 3 instead of it being a function of the sub-set size? 

Thanks.
Obonu Klu

**Comment by ALandauer** [comment]
Hi Obonu,
I'll just go ahead and answer in order:
(A) Subsets are sampled from the images on the mesh, such that computed displacements are on mesh nodes; so basically yes, but saying they are "spatially linked" does not really have a strong definition in the context of this code.

(B) The "dm" is the grid spacing of the (by default) square mesh and at each node (i.e. every "dm") a subset is taken and displacements are computed.   Since this is an Eulerian mesh, we then interpolate the displacement guess back onto reference configuration mesh nodes at each iteration in the IDM (du). 

(C) I'm not exactly certain what you mean; with DVC you will never really be able to get the "actual" displacement at a point since it is inherently subset based (something like T-PT would get you a lot closer) and will have some amount of local averaging.  Decreasing subset spacing will more densely sample the image, but subsets overlap and the unique information density is basically fixed. If you need to get close to a boundary or have low resolution images it can in some cases improve things to reduce final subset spacing, but in general it is unnecessary. 

(D) If you need dm=3 then by all mean change dm. We use dm=8 because it is typically a good balance of sampling density to computational cost for our image sizes.

Regards,
Alex
