### ISSUE TITLE
Registration 3D images using FIDVC

### ISSUE THREAD

**Issue by schweini2409** [FranckLab/FIDVC#27]
Hello,
I'd like to align 2 stacks of images so I'm wondering whether I can use FIDVC to find the displacement between the two stacks then apply this displacement to one of the images for the registration? 
Thank you,

**Comment by mohakpatel** [comment]
Yes, that should work. You will have to take mode of the displacement to get the most accurate estimation of the rigid displacement between the two images. 

If you have 2D images, you can use https://github.com/FranckLab/qDIC.

**Comment by schweini2409** [comment]
Then I suppose that I can use the volumeMapping.m to apply the displacement found previously to the volume ?

**Comment by ALandauer** [comment]
The volumeMapping function is probably a bit too specialized since it does
both the forward and backward mapping. A simpler solution is to either
re-interpolate onto a shifted grid or use the Matlab built-in affine3d (and
related) function.

For an example of re-interpolation look at volumeMapping, but only
implement the "forward" part with a single uniform value of displacement
measured from running FIDVC. Although, you can use Matlab built-in
interpolation instead of the mex interpolation, since you'll only need to
do it once.
