### ISSUE TITLE
acceleration using gpu

### ISSUE THREAD

**Issue by guava1427** [FranckLab/FIDVC#28]
Hello, I'm trying to use FIDVC for the measurement of 3D displacements.

Currently, the calculation is being done by CPU, but I want to use GPU for the fast computation.
How can I use GPU for this package? Thank you.

**Comment by jyang526843** [comment]
Hello, thank you for the reach out! 

I remember our previous GPU implementation uses some toolbox developed by a company, which is not freely available anymore. Mathworks has some GPU interface as well but I don't think we have implemented that yet. 

We will appreciate you or someone else who is interested in developing new GPU features and can help contribute to the FIDVC code. You can fork our repository and pull requests if you make changes. 

I am also wondering how big is your dataset. FIDVC employs some adaptive-mesh calculation and usually runs very fast. Sometimes even you apply the GPU to perform parallel computing, however, the time cost of data transferring (volumetric image size can be huge) can be significantly increased as well. So do you really need to use the GPU computation?

Best regards,
Jin

**Comment by ALandauer** [comment]
To expand on that slightly: the original results for GPU computation reported in the paper used the AccelerEyes Jacket toolbox, which was purchased by Mathworks and subsequently discontinued (in about 2013 if I recall properly).  We haven't updated the code for more recent GPU computing built-in functions in Matlab. 

I did a few basic tests using the Matlab GPU compute functions a few years ago and found that for the GPU features Matlab had available at that point, the efficiency gain was much smaller than what Eyal had found with the Jacketized version. Likely due to how their implementation does memory management (I think).  Newer versions of Matlab might be better though, so as Jin mentioned feel free to try it out. We're happy to help if you run in to questions. As an entry point, the major target for speeding up with GPU compute (in my mind) is the FFT-based matching found in the DVC.m. Good luck!

**Comment by guava1427** [comment]
Thank you for your comments. I would try to use GPU for your program, though it may not be as successful as the expectation. DVC.m may be a good starting point. Thanks a lot.
