### ISSUE TITLE
Index exceeds matrix dimensions error message 

### ISSUE THREAD

**Issue by ragyei** [FranckLab/FIDVC#4]
Hello Mohak, I downloaded the new version of the FIDVC software and run the software with the available example volume data. i made changes to the subset size in the main file and run and the following error keeps appearing 

Index exceeds matrix dimensions.

Error in funIDVC>loadFile (line 80)
I = load(fileInfo.filename{idx});

Error in funIDVC (line 54)
I{1} = loadFile(fileInfo,1);

Error in exampleRunFile (line 73)
[u, cc, dm] = funIDVC(filename, sSize, incORcum);

any suggestions?

Thank you.
Ronald Agyei.

**Comment by mohakpatel** [comment]
Hi Ronald,
What was the new subset size that you prescribed in the main file?

Best,
Mohak

**Comment by ragyei** [comment]
Hi Mohak,
The subset size im using is 32 by 32 by 32 since i want better resolution for my strains and i get the consistent error that reads 

Subscript indices must either be real positive integers or logicals.

Error in checkConvergenceSSD (line 76)
            dSSE = diff(SSE(idx)); % calculate difference

Error in IDVC (line 60)
     [converged01, SSE(i-1) , sSize(i,:), sSpacing(i,:)] = checkConvergenceSSD(I,SSE,sSize,sSpacing,convergenceCrit);

Error in funIDVC (line 65)
    [u_, cc{i-1}, dm] = IDVC(I,sSize0,u_);

Error in exampleRunFileSmallest (line 75)
[u, cc, dm] = funIDVC(filename, sSize, incORcum);

**Comment by therewasnootherusername** [comment]
I have the same error with the subset size of 32 x 32 x 32.

**Comment by mohakpatel** [comment]
That is odd. I'm having a look at it. Will let you know about it.

**Comment by mohakpatel** [comment]
Hi Ronald, 

Thanks for pointing this issue. We found a bug in our code which caused this error. We just fixed it and have shipped a [new release](https://github.com/FranckLab/FIDVC/releases) which takes care of this issue. You should now be able to use subset size of [32,32,32]. Once again, thanks for pointing out about issue which allowed us to fix it. 

One thing that will be useful to know is that FIDVC follows refinement of window size. This means that you can start with a bigger window size (ex [128,128,64]), and then the code iteratively solves for displacement field while refining the window size. This goes on till window size has been reduced to [32,32,32] and the convergence criteria has been met. So you don't need to start with window size of [32,32,32], you will get to it during refinement. Moreover, it's a good idea to start with bigger window size in beginning, so that you don't loose any large deformations. 

I hope this helps. 

Best,
Mohak
