### ISSUE TITLE
Why displacement changes by using different dm "desired output mesh spacing"

### ISSUE THREAD

**Issue by Erfan453** [FranckLab/FIDVC#7]
Hello,

I really appreciate if you please clarify the the role of dm = 8 ( desired output mesh spacing). For my images, I'm using the minimum spacing size of [16 16 16], however, when I use different dm=4,8,16, the results will be different. Since the dm has used in addDisplacements function to make new grid, I was wondering if I should consider the same number as the minimum spacing (Because in last step minimum spacing will be used: as a result, in order to get the output of exact nodal displacement (without interpolation), dm should be the same as the last step spacing). 

Also, if dm is for output , why the displacement will change by dm choice.

Thanks in advance
Yours sincerely

**Comment by mohakpatel** [comment]
I don't understand your question. But I will try to answer few of the points. 

I don't know how you assigned "minimum spacing" as [16 16 16]. In the exampleRunFile, you can only assign the initial subset size (sSize). So did you change the subset size?

The final minimum subset spacing can be selected through choice of dm as preset condition in IDVC.m. Depending on dm and initial size of volume (I), the final size of each component of u, ie u{1,1}{1,1} will be: 1:dm:size(I,1)+dm. So dm decides the size of displacement grid. 

Let me know if this helps or if you have more questions.

**Comment by Erfan453** [comment]
Hello,
Many thanks for your help. 
In checkConvergenceSSD function, sSize and sSpacing are refining until:

 % window spacing refinement. Only do if the sSpacing > 8 voxels
 if (sSpacing0 > 8), sSpacing1 = sSize1/2;

And then:

 % if dSSE meets first convergence criteria then refine spacing
 % to the minimum value, 8 voxels.
  if dSSE(end) <= convergenceCrit(1)
   sSize1 = sSize0; sSpacing1 = [8 8 8]; 
   end

In DVC function, using the last step spacing  (DVC(I,sSize(i,:),sSpacing(i,:),DVCPadSize,ccThreshold);), the correlation will compare subsets with spacing of sSpacing(i,:). As a result, the result will be the displacement of grids with the same spacing. And in order to be summed with du of the previous step, the displacement will be interpolated with spacing of dm.

So my question is that if in checkConvergenceSSD, I change the minimum sSpacing to [16 16 16] and initial subset size of [128 128 64], what should I choose for dm to get the right answer? Is there any criteria for choosing dm?

Many thanks for your kind consideration
Yours sincerely

**Comment by mehrdadhosseini** [comment]
Hello, 
 I have the same question but I could not get the answer by reading the response. I am getting a large variation in displacement by changing the choice of dm. For instance, I have 50% difference in u{1}{1}(1,1,1) between dm=4 and dm=8. If the size of displacement u{1}{1} is "1:dm:size(I,1)+dm" then logicaly  at least the first array u{1}{1}(1,1,1)  should be independent of dm.  I was wondering what is the reason for this large difference. Please correct me if I am getting something wrong. 

I would appreciate your help.

Thanks

**Comment by FranckLab** [comment]
Greetings, this is Alex Landauer, a PhD student in the Franck Lab.  I realize it’s been a few months, but I noticed this was still an open question, so I will propose an answer.  

You can think of the "dm" as a control in the spatial filtering operation, both as a parameter of `filterDisplacements` and a refinement control.  Thus, changing dm will change the noise content of the image, which should be particularly noticeable at the edges (i.e. u{1}{1}(1,1,1)) since the matching inversion is less well posed.

I would expect the displacement you reconstruct to change somewhat with choice of "dm" and with dm != sSpacing you will either subsample or supersample the actual interrogation points. This may lead to unpredictable behavior that is outside the scope of our typical validation procedures.  I would suggest that interpolation on the displacement is more predictable and reliable, and to let dm and minimum subset spacing be equal.

One final point, the "right" answer from any physical measurement technique, particularly one as abstracted as DIC, depends on the what you need to measure.  There is a balance between noise floor and resolution, and you need to know your problem and establish sensible measurement practices with respect to it.

Let us know if you still have questions.
