### ISSUE TITLE
How do the coordinates in the displacement matrices, u{1}{1:3}, correlate to the coordinates of the original volume?

### ISSUE THREAD

**Issue by MColasurdo** [FranckLab/FIDVC#8]
Hello!

I see that if I have an image that is 512 x 512 x 64, my displacement matrices will be 65 x 65 x 9, which means each dimension of the displacement matrix is the dimension of the volume divided by the spacing size (dm) and then increased by 1:

By default, dm=8, so:

(512/8)+1=65; (512/8)+1=65; (64/8)+1=9.

Why are the dimensions increased by 1? Where do these points exactly correlate to in the original volume? For example, if i have a volume that's 512 x 512 x 64 and set my dm=1, would my displacement matrices be of size 513 x 513 x 65? What position in the original volume would position (513, 513, 65) in the displacement image correspond to if the original image is only 512 x 512 x 64? 

Thank you!

**Comment by mohakpatel** [comment]
The displacement grid is generated as follows:
`1 : dm : size(I,1)+dm`, `1 : dm : size(I,2)+dm` & `1 : dm : size(I,3)+dm` 

Here, `I` is the volume. This grid position tells you how the displacement are related to the original volume. 

Yes, if you have 512x512x64 volume, you will have 513x513x65 displacement grid size. The displacement matrix in this case directly tells the position of displacement in the original volume since the dm =1.

I hope this helps.
